### PR TITLE
fix: Work around google_tag cache clear NFS lock issues.

### PR DESCRIPTION
**Pull request by cafuego**
This will also solve its opninions on directrory permissions, which break restic backups.

Note that I have not tested this code on a Drupal, only on a local test directory. Ensure it works by doing some cache clears on a non-prod site and checking that nothing breaks.

Refs: OPS-7514

### CODE REVIEW

**Comment by berliner** [comment]
Can we switch back to the original mariadb image so that the checks pass? I'm not sure I understand why you changed that. Apart from that this looks good. I only tested on my local (where I didn't see an issue anyway, so probably want to deploy this to stage dev to test there.

**Comment by berliner** [comment]
@cafuego Just tried to deploy a tagged image with the changes from this PR included, but it failed, this time with a different error. Can you have another look at this? I have re-deployed main for the moment, but feel free to try again with the v1.0.0 image.

**Comment by cafuego** [comment]
Ah yep, hat's google_tag setting stupid permissions initially. I see it all ended up working (except for that stack PR that would've matched an un-merged one) for v1.0.0. All sorted now I think.

**Comment by berliner** [comment]
@cafuego All fine it seems. Serban adjusted the permissions on the directory and then the deployment worked. I did another deployment to see if the permissions now persisted on the directory because it's not removed anymore and that worked. So all good from my side. Thank you very much!

**Pull request merged**
