### PR TITLE
fix: Update the theme build and enable webp support.

### PR DESCRIPTION
**Pull request by cafuego**
Refs: OPS-8805 OPS-8827

### CODE REVIEW

**Comment by cafuego** [comment]
Also checking if @left23 has a better idea for my common_design subtheme hack.

**Review by berliner — APPROVED** [review]

**Comment by berliner** [comment]
Let's try that

**Comment by berliner** [comment]
That fixed the build error! Cool. Still wondering though why I don't need to do that on my local.

**Comment by left23** [comment]
I'm looking into this a bit now. I wonder @berliner do you also run `npm i` in the Drupal core directory? This might be something that happens on the server, that we don't always do (or need to do) locally. It _might_ reproduce the issue with the stylelint version conflict. I'll let you know if I find anything helpful today but it will also be hard for me to debug without a local site to test.

**Comment by berliner** [comment]
No I don't do that I think. Just running `npm install` and the sass build directly inside the common design subtheme folder. Don't waste time on this though, it's not very important ;) I was just wondering.

**Comment by left23** [comment]
When I run `npm audit fix` in the sub theme locally, I can reproduce this error. This is regardless of installing the Drupal core node packages.
I checked to see if I can also reproduce it in the base theme or its subtheme (from the https://github.com/UN-OCHA/common_design) and I don't get this error in that case, so it seems it's specific to this site set up but I can't see obviously why. Since this isn't blocking, I will leave it there, as I think @cafuego 's solution is sound (and the one recommended in the error's output). Feel free to ping me again if I should look more into it, or if new information comes to the fore.

**Pull request merged**
