### PR TITLE
GHI-36: Enforce JIRA ticket number in commit message

### PR DESCRIPTION
**Pull request by berliner**

### CODE REVIEW

**Review by attiks — APPROVED** [review]

**Review by rupl — APPROVED** [review]
In general I feel like if we're writing a script that has explicit instructions to append a string, the script should just do that instead of slapping our wrists and causing us to try again.

However I tried messing with the script to automate prepending the ticket number, but after a half hour it felt like I wasted more time than I'd have eventually saved so I gave up.

**Comment by berliner** [comment]
@rupl There might be a misunderstanding about what this script is trying to do. It was not mend to change the commit message in any way, so it does not try to append a string somewhere. Instead it tries to enforce a convention (if a GHI ticket number is the first part of a branch name's last segment, behind a possible slash-separated prefix, e.g. `GHI-36` or `rbaumbach/GHI-36`, then it insists that the commit message starts with that string "GHI-36"), by checking and comparing the branch names with the commit messages. I personally don't like automatic modifications of commit messages very much, but that's a personal thing. I had this script in my own global git hooks repository for a couple of years now, and just adapted it for GHI.

**Comment by attiks** [comment]
> I personally don't like automatic modifications of commit messages very much

same here

**Comment by rupl** [comment]
There was no misunderstanding, but out of the team, I seem to prefer the other approach.

No problem though; in the end I'm also happier with all commits having a defined prefix (however it arrives there!)

**Pull request merged**
