### PR TITLE
HPC-9544: Allow granting admin rights to others.

### PR DESCRIPTION
**Pull request by aessid**

### CODE REVIEW

**Review by berliner — CHANGES_REQUESTED** [review]
While it technically solves the issue, it also allows administrators to change permissions on all roles, which is not what we want. We don't want anyone else besides user 1 to be able to modify permissions, in other words, accessing the permissions page.
Also adding this to the ticket.

**Comment by aessid** [comment]
@berliner I wasn't expecting this behavior
Screenshot from 2024-06-18 09-38-52

**Comment by berliner** [comment]
That's a bit confusing indeed. The first "Roles" block is the default drupal one, the second one comes from the role delegation module. Removing the 'administer user roles' permission, removes the first, default, block. The second one can be made complete by giving administrators the permission 'assign all roles'.
See https://github.com/UN-OCHA/ghi-site/pull/1063

There is still an additonal "Roles" tab on the user edit page. This is provided by the role delegation module, and it's sole purpose is to change roles of a user. We don't need that, but it doesn't hurt either, so it's fine with me.

**Comment by aessid** [comment]
@berliner tested, looks good and ready to go.

**Pull request merged**
